version: '3.7'

services:
  backend_test:
    container_name: BackendTest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - backend_test_logs:/code/logs
    networks:
      nginx_net1:
        ipv4_address: 172.77.0.3

volumes:
  backend_test_logs:

networks:
  nginx_net1:
    external:
      name: nginx-net
