version: '3.7'

services:
  backend_test:
    container_name: BackendTest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - backend_test_logs:/app/logs
    networks:
      nginx_net1:

volumes:
  backend_test_logs:

networks:
  nginx_net1:
    external:
      name: nginx-net
