version: '3.7'

services:
  backend_test:
    container_name: algoscalc-back.local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
    env_file:
      - .env.local
    command: .venv/bin/python -m uvicorn "src.main:create_app" --host=0.0.0.0 --port=8080 --reload
